"""Data-only Page 06 oracle for contract-clause routing and risk rules.

This module imports no production code. It records exactly ``CLAUSES-F01``
through ``CLAUSES-F19`` and the source surfaces needed for the D2
transcription. Money is integer cents; exact ratios use ``Decimal``.
"""

from decimal import Decimal
from typing import Final

PAGE_06_SOURCE_SECTIONS: Final = (
    "metadata_and_target",
    "1_purpose",
    "2_legal_basis",
    "3_inputs",
    "4_formula_b1_b8",
    "5_edge_cases_e1_e11",
    "6_examples_clauses_f01_f19",
    "7_out_of_scope",
)

PAGE_06_REGISTER_PAGE: Final = (
    "06 · Vertragsklauseln — Risiko-Memo "
    "(https://app.notion.com/p/06-Vertragsklauseln-Risiko-Memo-"
    "3ab5fd420731813799c0c1b419eac4f3?pvs=21)"
)

# Wert, Betrag / Satz, Flag, Letzte Änderung um, Prüfen bis, Quelle,
# Rechtsgrundlage §, Rechtsnatur, Rechtsstand. The omitted page is the shared
# PAGE_06_REGISTER_PAGE above. Order matches the authoritative CSV.
PAGE_06_REGISTER_ROWS: Final[tuple[tuple[str, ...], ...]] = (
    (
        "Schriftform Staffel-/Indexklausel",
        "QES oder Papier; einfache E-Signatur (Textform) unzureichend → Klausel unwirksam",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "https://www.gesetze-im-internet.de/bgb/__557a.html",
        "§ 557a Abs. 1, § 557b Abs. 1, § 126/126a BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Mietpreisbremse (§ 556d)",
        "+10 % über Vergleichsmiete; verlängert bis 31.12.2029",
        "geprüft",
        "28. Juli 2026 22:14",
        "31. Dezember 2029",
        "https://www.bundestag.de/dokumente/textarchiv/2025/kw26-de-mietpreisbremse-1084786",
        "§ 556d BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Kappungsgrenze angespannter Markt (§ 558)",
        "15 % / 3 Jahre (Geltungsgebiet je LandesVO)",
        "verify-before-production",
        "28. Juli 2026 22:14",
        "5. August 2026",
        "https://dejure.org/gesetze/BGB/558.html",
        "§ 558 Abs. 3 S. 2 BGB + LandesVO",
        "Verordnung",
        "07/2026",
    ),
    (
        "Formzwang befristeter Vertrag über 1 Jahr",
        "Schriftform; Verstoß → gilt als unbefristet (nicht nichtig)",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "",
        "§ 550 BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Verzugsschwelle fristlose Kündigung",
        "über 1 Monatsmiete (2 Termine) bzw. ≥ 2 Monatsmieten (längerer Zeitraum)",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "",
        "§ 543 Abs. 2 Nr. 3, § 569 Abs. 3 BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Indexmiete VPI-Bindung (§ 557b)",
        "VPI Destatis; Änderung ≥ 12 Monate; Änderungserklärung in Textform "
        "[UNSICHER: Mietrecht II plant Einschränkung]",
        "verify-before-production",
        "28. Juli 2026 22:14",
        "31. Dezember 2026",
        "https://dejure.org/gesetze/BGB/557b.html",
        "§ 557b BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Kappungsgrenze Standard (§ 558)",
        "20 % / 3 Jahre",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "https://dejure.org/gesetze/BGB/558.html",
        "§ 558 Abs. 3 BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Kleinreparaturen Jahresgrenze",
        "ca. 6 % der Jahresnettokaltmiete",
        "verify-before-production",
        "28. Juli 2026 22:14",
        "5. August 2026",
        "",
        "§ 307 BGB (Rspr., kein gesetzlicher Wert)",
        "Konvention",
        "07/2026",
    ),
    (
        "Schonfristzahlung ordentliche Kündigung (geplant)",
        "Ausweitung geplant, am 09.07.2026 NICHT in Kraft (BT-Drs. 21/6807, 1. Lesung)",
        "verify-before-production",
        "28. Juli 2026 22:14",
        "31. Dezember 2026",
        "https://www.haufe.de/recht/weitere-rechtsgebiete/miet-immobilienrecht/"
        "mietrechtsreform-2026_214_684532.html",
        "§ 569 Abs. 3 BGB (Entwurf Mietrecht II)",
        "Gesetz",
        "07/2026",
    ),
    (
        "Modernisierung Umlagesatz (§ 559)",
        "8 % p. a. der auf die Wohnung entfallenden Kosten",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "https://dejure.org/gesetze/BGB/559.html",
        "§ 559 Abs. 1 BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Signatur-Gate V1",
        "einfache E-Signatur nur ohne Staffel/Index freigeschaltet",
        "verify-before-production",
        "28. Juli 2026 22:14",
        "5. August 2026",
        "",
        "Produktregel (abgeleitet aus § 557a/b, § 550)",
        "Konvention",
        "07/2026",
    ),
    (
        "Kleinreparaturen Einzelgrenze",
        "ca. 100,00 € je Reparatur",
        "verify-before-production",
        "28. Juli 2026 22:14",
        "5. August 2026",
        "",
        "§ 307 BGB (Rspr., kein gesetzlicher Wert)",
        "Konvention",
        "07/2026",
    ),
    (
        "Staffelmiete Mindestintervall (§ 557a)",
        "Miete je Stufe ≥ 12 Monate unverändert; Betrag absolut auszuweisen",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "https://www.gesetze-im-internet.de/bgb/__557a.html",
        "§ 557a Abs. 1, 2 BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "§ 556d Handling (Produkt)",
        "warn-only + dokumentierte Selbstauskunft, kein Block",
        "verify-before-production",
        "28. Juli 2026 22:14",
        "5. August 2026",
        "",
        "§§ 556d–556f BGB",
        "Konvention",
        "07/2026",
    ),
    (
        "Kaution (§ 551)",
        "max 3 Nettokaltmieten, zahlbar in 3 Raten",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "",
        "§ 551 Abs. 1, 2 BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "Modernisierung Kappung (§ 559)",
        "3 €/m² (2 €/m² wenn Ausgangsmiete unter 7 €/m²) in 6 Jahren",
        "geprüft",
        "28. Juli 2026 22:14",
        "",
        "https://www.gesetze-im-internet.de/bgb/__559.html",
        "§ 559 Abs. 3a BGB",
        "Gesetz",
        "07/2026",
    ),
    (
        "SEPA-Lastschriftmandat — Einzug/Verfall",
        "Einzug erfordert Gläubiger-ID + PIS; Mandat verfällt 36 Monate nach letzter Nutzung",
        "verify-before-production",
        "29. Juli 2026 14:07",
        "5. August 2026",
        "",
        "SEPA-Rulebook / VO (EU) 260/2012",
        "Verordnung",
        "07/2026",
    ),
)

FORMULA_IDS: Final = tuple(f"B{number}" for number in range(1, 9))
EDGE_CASE_IDS: Final = tuple(f"E{number}" for number in range(1, 12))

PAGE_06_NON_GOALS: Final = (
    "Gewerberaum-Klauseln",
    "Staffel-/Index-Mischklauseln in einem Vertrag",
    "QES-Integration für formgebundene Verträge",
    "Automatische Prüfung/Berechnung der § 556d-Ausnahmen",
    "Anwaltliche Wirksamkeitsprüfung im Einzelfall",
    "Individuell ausgehandelte (nicht formulierte) Klauseln",
    "Modernisierungsankündigung (§ 555c, Fristen)",
)

PAGE_06_SOURCE_EXCLUSIONS: Final = (
    "Gewerberaummietverträge",
    "WEG-/Sondereigentumsvereinbarungen",
    "Staffel-/Index-Mischklauseln",
    "individuell ausgehandelte Klauseln",
    "anwaltliche Wirksamkeitsprüfung im Einzelfall",
    "QES-Integration für formgebundene Verträge",
    "automatische Prüfung/Berechnung der § 556d-Ausnahmen",
    "Modernisierungsankündigung (§ 555c, Fristen)",
    "Mietpreisbremsen-Rüge/Auskunft des Mieters",
    "SEPA-Lastschrift-Einzug/-Ausführung",
    "steuerliche Berechnung der Eigennutzung",
)

FUTURE_CONTRACTS: Final = (
    "versioned_clause_reference",
    "contract_composition",
    "compatibility_and_signature_gate",
    "immutable_risk_result",
    "sepa_mandate_capture",
    "action_workflow_input",
)

UNRESOLVED_AUTHORITY: Final = (
    "index_decline_product_behavior",
    "section_559_six_year_window_start",
    "state_regulation_coverage",
    "small_repair_default_limits",
    "planned_tenancy_law_ii_changes",
    "sepa_mandate_expiry",
    "fixed_term_signature_fixture",
)

MISSING_SOURCE_CATALOGUES: Final = (
    "complete_clause_text_and_version_catalogue",
    "complete_rent_increase_letter_body",
    "complete_termination_letter_body",
    "complete_reminder_letter_body",
)

COMPATIBILITY_ANCHORS: Final = {
    "docs/10-afa.md": "self_use_reduces_deductible_afa_not_basis",
    "docs/11-tax-export.md": "tax_income_and_cash_basis_owned_by_page_04",
    "docs/12-guards-deadlines.md": "dates_thresholds_and_guard_state_owned_by_page_05",
    "superseded_page_06_wording": "afa_basis_reduction",
}

ARITHMETIC_AUDIT: Final = {
    "fixture_count": 19,
    "fixture_range": "CLAUSES-F01…CLAUSES-F19",
    "printed_cent_arithmetic": "exact",
    "clears_unverified_values": False,
}

PAGE_06_GOLDENS: Final[dict[str, dict[str, object]]] = {
    "CLAUSES-F01": {
        "rule": "B1",
        "previous_rent_cents": 80_000,
        "increase_cents": 2_500,
        "interval_months": 12,
        "next_absolute_rent_cents": 82_500,
        "effective": True,
    },
    "CLAUSES-F02": {
        "rule": "B2",
        "old_rent_cents": 90_000,
        "old_index": Decimal("118.5"),
        "new_index": Decimal("122.7"),
        "factor": Decimal("1.035443037974683544303797468"),
        "unrounded_new_rent_cents": Decimal("93189.87341772151898734177215"),
        "new_rent_cents": 93_190,
        "interval_months": 12,
    },
    "CLAUSES-F03": {
        "rule": "B3a",
        "current_rent_cents": 70_000,
        "comparative_rent_cents": 90_000,
        "cap_rate": Decimal("0.20"),
        "cap_cents": 84_000,
        "target_rent_cents": 84_000,
        "increase_cents": 14_000,
    },
    "CLAUSES-F04": {
        "rule": "B3b",
        "current_rent_cents": 70_000,
        "comparative_rent_cents": 90_000,
        "cap_rate": Decimal("0.15"),
        "cap_cents": 80_500,
        "target_rent_cents": 80_500,
        "increase_cents": 10_500,
    },
    "CLAUSES-F05": {
        "rule": "B4a",
        "modernization_cost_cents": 2_000_000,
        "annual_rate": Decimal("0.08"),
        "annual_allocation_cents": 160_000,
        "monthly_unrounded_cents": Decimal("13333.33333333333333333333333"),
        "monthly_cents": 13_333,
        "area_sqm": Decimal("60"),
        "starting_rent_cents_per_sqm": 800,
        "cap_cents_per_sqm": 300,
        "cap_cents": 18_000,
        "increase_cents": 13_333,
    },
    "CLAUSES-F06": {
        "rule": "B4b",
        "modernization_cost_cents": 2_000_000,
        "annual_rate": Decimal("0.08"),
        "annual_allocation_cents": 160_000,
        "monthly_cents": 13_333,
        "area_sqm": Decimal("60"),
        "starting_rent_cents_per_sqm": 650,
        "cap_cents_per_sqm": 200,
        "cap_cents": 12_000,
        "increase_cents": 12_000,
    },
    "CLAUSES-F07": {
        "rule": "B5",
        "single_limit_cents": 10_000,
        "annual_net_cold_rent_cents": 840_000,
        "annual_limit_rate": Decimal("0.06"),
        "annual_limit_cents": 50_400,
        "repairs_cents": (8_000, 9_500, 12_000, 7_000, 9_000),
        "chargeable_repairs_cents": (8_000, 9_500, 0, 7_000, 9_000),
        "renter_share_cents": 33_500,
        "landlord_share_cents": 12_000,
        "limits_unverified": True,
    },
    "CLAUSES-F08": {
        "rule": "B6",
        "net_cold_rent_cents": 70_000,
        "maximum_deposit_cents": 210_000,
        "installment_count": 3,
        "installment_cents": 70_000,
        "installment_sum_cents": 210_000,
    },
    "CLAUSES-F09": {
        "rule": "B7a",
        "gross_monthly_rent_cents": 85_000,
        "open_installments_cents": (85_000, 85_000),
        "arrears_cents": 170_000,
        "threshold_cents": 85_000,
        "comparison": "strictly_greater",
        "eligible": True,
    },
    "CLAUSES-F10": {
        "rule": "B7b",
        "gross_monthly_rent_cents": 85_000,
        "monthly_shortfall_cents": 35_000,
        "month_count": 5,
        "arrears_cents": 175_000,
        "threshold_cents": 170_000,
        "comparison": "greater_or_equal",
        "eligible": True,
    },
    "CLAUSES-F11": {
        "edge": "E1",
        "old_rent_cents": 90_000,
        "old_index": Decimal("118.5"),
        "new_index": Decimal("117.0"),
        "factor": Decimal("0.9873417721518987341772151899"),
        "unrounded_new_rent_cents": Decimal("88860.75949367088607594936709"),
        "calculated_rent_cents": 88_861,
        "automatic_adjustment": False,
        "product_behavior": "unresolved",
    },
    "CLAUSES-F12": {
        "edge": "E2",
        "previous_rent_cents": 80_000,
        "proposed_rent_cents": 82_500,
        "interval_months": 10,
        "effective": False,
        "resulting_rent_cents": 80_000,
    },
    "CLAUSES-F13": {
        "edge": "E3",
        "current_rent_cents": 70_000,
        "comparative_rent_cents": 75_000,
        "cap_rate": Decimal("0.20"),
        "cap_cents": 84_000,
        "target_rent_cents": 75_000,
        "increase_cents": 5_000,
        "workflow": "existing_tenancy_rent_increase",
    },
    "CLAUSES-F14": {
        "edge": "E4",
        "area_sqm": Decimal("60"),
        "cap_cents_per_sqm": 300,
        "six_year_cap_cents": 18_000,
        "first_increase_cents": 13_333,
        "second_unconstrained_increase_cents": 13_333,
        "unconstrained_cumulative_cents": 26_666,
        "second_allowed_increase_cents": 4_667,
        "resulting_cumulative_cents": 18_000,
        "window_start": "unresolved",
    },
    "CLAUSES-F15": {
        "edge": "E8",
        "clause": "graduated_rent",
        "signature": "simple_e_signature_text_form",
        "signature_gate": "blocked",
        "route": "paper_or_qes",
        "initial_rent_cents": 80_000,
        "cent_result": None,
        "fixed_term_over_one_year_fixture_present": False,
    },
    "CLAUSES-F16": {
        "rule": "B8",
        "edge": "E9",
        "comparative_rent_cents": 90_000,
        "maximum_rent_rate": Decimal("1.10"),
        "maximum_rent_cents": 99_000,
        "agreed_rent_cents": 105_000,
        "excess_cents": 6_000,
        "exception": "none",
        "outcome": "warn_only_continue",
        "rent_capped_by_lokara": False,
        "self_declaration_recorded": True,
    },
    "CLAUSES-F17": {
        "rule": "B8",
        "edge": "E9",
        "comparative_rent_cents": 90_000,
        "maximum_rent_cents": 99_000,
        "agreed_rent_cents": 105_000,
        "exception": "previous_rent",
        "exception_verified_by_lokara": False,
        "outcome": "notice_continue",
        "rent_capped_by_lokara": False,
        "timestamp_required": True,
    },
    "CLAUSES-F18": {
        "edge": "E10",
        "mandate_reference": "MIETE-2026-WE02-014",
        "reference_length": 19,
        "maximum_reference_length": 35,
        "mandate_date": "2026-07-28",
        "today": "2026-07-29",
        "status": "complete_no_collection_v1",
        "future_date": "2026-09-01",
        "future_date_valid": False,
        "future_date_blocks_contract": False,
        "collection_enabled": False,
    },
    "CLAUSES-F19": {
        "edge": "E11",
        "self_use": True,
        "area_sqm": Decimal("60"),
        "period": "full_year",
        "tenancy_created": False,
        "rent_clause_routes_active": False,
        "page_03_route": "self_use_period_reduces_deductible_afa",
        "page_03_afa_basis_reduced": False,
        "page_04_tax_income_cents": 0,
        "page_06_cent_result": 0,
        "source_basis_wording_superseded": True,
    },
}
