"""Data-only Page 05 oracle for the guards/deadlines transcription.

This module imports no production code. It records exactly ``12-F01`` through
``12-F24`` and the source surfaces needed to prove the D2 transcription.
"""

PAGE_05_GOLDENS: dict[str, dict[str, object]] = {
    "12-F01": {
        "guard": "W1",
        "period_end": "2025-12-31",
        "today": "2026-12-01",
        "delivered_on": None,
        "deadline": "2026-12-31",
        "days_until_deadline": 30,
        "stage": "reminder_30_days",
        "channels": ("in_app", "email"),
    },
    "12-F02": {
        "guard": "W1",
        "period_end": "2024-02-29",
        "today": "2025-01-15",
        "deadline": "2025-02-28",
        "days_until_deadline": 44,
        "stage": "none",
    },
    "12-F03": {
        "guard": "W1",
        "period_end": "2025-12-31",
        "today": "2027-01-15",
        "delivered_on": None,
        "deadline": "2026-12-31",
        "days_until_deadline": -15,
        "stage": "expired",
        "credit_remains_payable": True,
    },
    "12-F04": {
        "guard": "W1",
        "period_end": "2025-12-31",
        "today": "2026-12-01",
        "delivered_on": "2026-12-20",
        "deadline": "2026-12-31",
        "resolved": True,
        "renter_objection_deadline": "2027-12-20",
    },
    "12-F05": {
        "guard": "W2",
        "medium": "warm_water",
        "calibration_month": "2020-06",
        "today_month": "2025-08",
        "years_by_medium": {
            "cold_water": 6,
            "warm_water": 6,
            "heat_meter": 6,
            "heat_exchanger_hot_water": 6,
            "electricity": 8,
            "gas": 8,
        },
        "years": 6,
        "valid_until": "2026-12-31",
        "months_until_expiry": 16,
        "stage": "none",
        "effective_from": "2021-11-04",
        "expiry_rule": "end_of_calendar_year",
        "verification_status": "geprüft",
        "transition": (
            "UNSICHER: applies to already-installed devices only by provider communication"
        ),
        "superseded_source_result": (
            "Page 05 prints Warmwasser 5 Jahre, 31.12.2025 and the Hinweis stage for this "
            "case. The unified six-year MessEV period moves it to 31.12.2026 and out of the "
            "<= 6 months notice window at heute=08.2025."
        ),
        "heating_cost_allocator_in_guard": False,
    },
    "12-F06": {
        "guard": "W2",
        "calibration_date": None,
        "stage": "missing_calibration_date",
        "calculation": None,
        "warning_de": "Eichdatum erfassen",
    },
    "12-F07": {
        "guard": "W3",
        "gross_monthly_rent_cents": 85_000,
        "open_installments_cents": (85_000, 85_000),
        "payments_cents": (),
        "arrears_cents": 170_000,
        "consecutive_open_dates": 2,
        "threshold_3a_cents": 85_000,
        "threshold_3b_cents": 170_000,
        "stage": "3a",
        "triggers_3a": True,
        "triggers_3b": False,
    },
    "12-F08": {
        "guard": "W3",
        "gross_monthly_rent_cents": 85_000,
        "arrears_cents": 85_000,
        "consecutive_open_dates": 2,
        "threshold_3a_cents": 85_000,
        "stage": "info_exactly_one_month",
        "triggers_3a": False,
    },
    "12-F09": {
        "guard": "W3",
        "gross_monthly_rent_cents": 85_000,
        "open_installments_cents": (85_000, 85_000, 85_000),
        "payments_cents": (20_000,),
        "arrears_cents": 235_000,
        "consecutive_open_dates": 3,
        "threshold_3b_cents": 170_000,
        "stage": "3b",
        "triggers_3b": True,
    },
    "12-F10": {
        "guard": "W3",
        "arrears_before_cents": 235_000,
        "payment_cents": 100_000,
        "arrears_after_cents": 135_000,
        "threshold_3a_cents": 85_000,
        "threshold_3b_cents": 170_000,
        "stage_before": "3b",
        "stage_after": "3a",
        "resolved": False,
        "disposition": "downgrade_3b_to_3a",
    },
    "12-F11": {
        "guard": "W4",
        "remote_readable": True,
        "last_uvi_sent_on": "2026-05-31",
        "today": "2026-07-05",
        "due_on": "2026-06-30",
        "uvi_in_current_month": False,
        "stage": "overdue",
    },
    "12-F12": {
        "guard": "W4",
        "remote_readable": False,
        "today": "2026-07-05",
        "uvi_guard_active": False,
        "retrofit_notice_active": True,
        "retrofit_deadline": "2026-12-31",
    },
    "12-F13": {
        "guard": "W4",
        "remote_readable": True,
        "last_uvi_sent_on": None,
        "start_month": "2026-05",
        "today": "2026-06-03",
        "due_on": "2026-06-30",
        "stage": "not_due",
    },
    "12-F14": {
        "guard": "W5",
        "net_cold_rent_cents": 80_000,
        "base_rent_3y_cents": 80_000,
        "comparative_rent_cents": 100_000,
        "tight_market": False,
        "cap_rate": "0.20",
        "cap_ceiling_cents": 96_000,
        "maximum_new_rent_cents": 96_000,
        "maximum_increase_cents": 16_000,
        "limiting_rule": "cap",
        "mode": "full_check",
    },
    "12-F15": {
        "guard": "W5",
        "net_cold_rent_cents": 80_000,
        "base_rent_3y_cents": 80_000,
        "comparative_rent_cents": 88_000,
        "tight_market": True,
        "cap_rate": "0.15",
        "cap_ceiling_cents": 92_000,
        "maximum_new_rent_cents": 88_000,
        "maximum_increase_cents": 8_000,
        "limiting_rule": "comparative_rent",
        "mode": "full_check",
    },
    "12-F16": {
        "guard": "W5",
        "last_increase_effective_on": "2025-03-01",
        "today": "2026-01-01",
        "earliest_declaration_on": "2026-03-01",
        "earliest_effective_on": "2026-06-01",
        "active": False,
    },
    "12-F17": {
        "guard": "W5",
        "request_received_on": "2026-04-10",
        "consent_deadline": "2026-06-30",
        "effective_on": "2026-07-01",
        "action_deadline": "2026-09-30",
    },
    "12-F18": {
        "guard": "W6",
        "schedule": (
            ("2025-01-01", 90_000),
            ("2026-01-01", 95_000),
            ("2027-01-01", 100_000),
        ),
        "today": "2026-01-05",
        "current_target_rent_cents": 90_000,
        "active_step_cents": 95_000,
        "adjustment_due": True,
        "minimum_interval_months": 12,
        "valid": True,
    },
    "12-F19": {
        "guard": "W6",
        "first_step_on": "2025-06-01",
        "next_step_on": "2026-03-01",
        "interval_months": 9,
        "minimum_interval_months": 12,
        "validation_error": True,
    },
    "12-F20": {
        "guard": "W7",
        "net_cold_rent_cents": 80_000,
        "base_index": "118.0",
        "new_index": "122.3",
        "base_year": 2020,
        "new_base_year": 2020,
        "minimum_interval_reached": True,
        "factor": "1.036440677966101694915254237",
        "unrounded_new_rent_cents": "82915.25423728813559322033896",
        "new_rent_cents": 82_915,
        "increase_cents": 2_915,
        "delta_percent_display": "3.64",
        "active": True,
        "deflation_index": "117.9",
        "deflation_active": False,
        "mismatched_basis_year": 2015,
        "mismatched_basis_calculation": None,
        "mismatched_basis_warning_de": "Index umrechnen (Umbasierung)",
    },
    "12-F21": {
        "guard": "W7",
        "last_adjustment_on": "2025-09-01",
        "today": "2026-03-01",
        "elapsed_months": 6,
        "minimum_interval_months": 12,
        "active": False,
    },
    "12-F22": {
        "guard": "W8",
        "last_tenancy_ended_on": "2026-05-31",
        "active_tenancy": False,
        "today": "2026-07-20",
        "target_rent_cents": 90_000,
        "vacancy_days": 50,
        "threshold_days": 30,
        "lost_rent_cents": 150_000,
        "active": True,
        "active_tenancy_variant_active": False,
    },
    "12-F23": {
        "guard": "W5",
        "net_cold_rent_cents": 80_000,
        "base_rent_3y_cents": 80_000,
        "comparative_rent_cents": None,
        "tight_market": False,
        "cap_rate": "0.20",
        "cap_ceiling_cents": 96_000,
        "maximum_new_rent_cents": 96_000,
        "maximum_increase_cents": 16_000,
        "mode": "cap_only",
        "legality_confirmed": False,
    },
    "12-F24": {
        "guard": "W5",
        "net_cold_rent_cents": 95_000,
        "base_rent_3y_cents": 80_000,
        "comparative_rent_cents": 90_000,
        "tight_market": False,
        "cap_rate": "0.20",
        "cap_ceiling_cents": 96_000,
        "maximum_new_rent_cents": 90_000,
        "maximum_increase_cents": 0,
        "active": False,
    },
}

PAGE_05_SOURCE_SECTIONS = (
    "metadata_and_scope",
    "1_purpose",
    "2_legal_basis_and_conventions",
    "3_inputs_and_providers",
    "4_formulas_warning_escalation_auto_resolution",
    "5_edge_cases_e1_e20",
    "6_worked_examples_12_f01_f24",
    "7_out_of_scope",
)

# These are the eighteen Page-05-specific CSV rows, lines 116-133 in the
# authoritative Rechtsstand register. Every one remains verify-before-production.
PAGE_05_REGISTER_ROWS = (
    "W5 · Ortsübliche Vergleichsmiete = Input, keine Beschaffung (KONVENTION-OVM)",
    "W4 · UVI-Fälligkeit Monatsende (KONVENTION-D3)",
    "W8 · Leerstands-Schwelle + Geld-Framing (KONVENTION-L1/L2)",
    "W5 · Mieterhöhung zur ortsüblichen Vergleichsmiete",
    "W5 · Angespannter Wohnungsmarkt = LandesVO (KONVENTION-MARKT)",
    "W3 · Fristlose Kündigung bei Zahlungsverzug",
    "W5 · Kappungsgrenze 20 % / 15 %",
    "W5 · Zustimmungs-/Wirksamkeits-/Klagefrist Mieterhöhung",
    "W3 · Erheblichkeitsschwelle Zahlungsverzug",
    "W3 · Bezugsgröße Verzug = Bruttowarmmiete (KONVENTION-B1)",
    "W1/W5 · Fristarithmetik Monatsaddition (KONVENTION-D1/D4/D5)",
    "W3 · Schonfristzahlung heilt fristlose Kündigung",
    "W2 · Eich-Gültigkeit endet zum Jahresende (KONVENTION-D2)",
    "W2 · Eichfrist je Messgerätart",
    "W6 · Staffelmiete",
    "W7 · VPI-Berechnung proportional + Snapshot (KONVENTION-VPI)",
    "W5/W7 · Bezugsgröße = Nettokaltmiete (KONVENTION-B3)",
    "W7 · Indexmiete",
)

PAGE_05_REGISTER_FLAGS = {row: "verify-before-production" for row in PAGE_05_REGISTER_ROWS}

PAGE_05_SHARED_REGISTER_ROWS = (
    "UVI-Turnus",
    "Abrechnungsfrist Betriebskosten",
    "Nachrüstfrist fernablesbare Ausstattung",
    "Einwendungsfrist des Mieters",
    "Kürzungsrecht — fehlende oder unvollständige § 6a-Information (UVI + Abrechnungs-Infoblock)",
    "Belegeinsicht — elektronische Bereitstellung zulässig (Wohnraum)",
)

PAGE_05_SHARED_REGISTER_FLAGS = {
    row: "verify-before-production" if row.startswith("Kürzungsrecht") else "geprüft"
    for row in PAGE_05_SHARED_REGISTER_ROWS
}

PAGE_05_NON_GOALS = (
    "sample_letters_and_text_blocks",
    "actual_email_and_push_delivery",
    "not_responsible_case_assessment",
    "ordinary_termination_section_573",
    "section_558a_evidence_and_rent_index_procurement",
    "section_559_and_section_556d_calculators",
    "state_regulation_lists",
    "vpi_rebasing_conversion",
    "limitation_period_for_additional_claims",
    "legal_advice_and_binding_declarations",
)
