"""Data-only, cent-exact oracle for original Page 08 and approved `docs/15`.

All thirteen promised cases are executable dictionaries.  This module contains
only source-stated values and imports no production code.
"""

from typing import Final

Golden = dict[str, object]


MATCHING_CONTRACT: Final[dict[str, object]] = {
    "weights": {
        "unique_iban": 60,
        "ambiguous_iban": 20,
        "exact_amount": 30,
        "payment_code": 15,
        "end_to_end_reference": 15,
        "surname": 10,
        "period": 5,
    },
    "confidence_cap": 100,
    "auto_requires_unique_known_iban": True,
    "review_floor": 40,
    "unmatched_maximum": 39,
    "potential_duplicate_result": "needs_review",
    "exact_reimport_result": "dedupe_by_provider_transaction_id",
    "designated_payment_precedes_fifo": True,
    "fifo_order": ("due_before_not_due", "older_before_newer"),
    "within_debt_order": ("costs", "interest", "principal"),
    "partial_component_method": "proportional_largest_remainder",
    "float_import_rounding": "decimal_round_half_up_to_cent",
    "account_scope_required_on": (
        "bank_transaction",
        "receivable",
        "renter_matching_profile",
        "match_proposal",
        "payment_ledger_entry",
        "iban_history",
    ),
    "cross_account_candidates": "forbidden",
    "payment_ledger": "append_only_with_compensating_reversals",
    "iban_history": "versioned_after_confirmed_non_null_match",
}


PAGE_08_GOLDENS: Final[dict[str, Golden]] = {
    "BANKMATCH-F01": {
        "executable": True,
        "amount": 108_000,
        "signals": (60, 30, 0, 0, 5),
        "confidence": 95,
        "decision": "auto_match",
        "settlement_order": "designated_period",
        "components_paid": (85_000, 15_000, 8_000),
        "assigned": 108_000,
        "open_after": 0,
        "status_after": "settled",
    },
    "BANKMATCH-F02": {
        "executable": True,
        "amount": 108_000,
        "signals": (0, 30, 10, 0, 0),
        "confidence": 40,
        "decision": "needs_review",
        "rank": 1,
        "assigned_before_confirmation": 0,
        "learns_non_null_iban_after_confirmation": True,
    },
    "BANKMATCH-F03": {
        "executable": True,
        "amount": 108_000,
        "open_before": 108_000,
        "known_iban": "unique",
        "purpose": "Miete Juli",
        "is_potential_duplicate": True,
        "potential_duplicate_is_distinct_transaction": True,
        "unique_iban_signal": 60,
        "potential_duplicate_decision": "needs_review",
        "assigned_before_confirmation": 0,
        "duplicate_confirmation_result": "discard_without_settlement",
        "assigned_after_duplicate_confirmation": 0,
        "genuine_payment_confirmation_result": "delegate_to_F04_fifo_and_credit",
        "exact_reimport_same_id": True,
        "exact_reimport_dedupe_stage": "before_channel_and_scoring",
        "exact_reimport_second_scoring": False,
        "exact_reimport_second_review": False,
        "exact_reimport_settlement_count": 1,
        "exact_reimport_total_assigned": 108_000,
    },
    "BANKMATCH-F04": {
        "executable": True,
        "amount": 220_000,
        "signals": (60, 0, 0, 0, 0),
        "confidence": 60,
        "decision": "auto_match",
        "settlement_order": "fifo",
        "receivables_paid": (108_000, 108_000),
        "credit": 4_000,
        "assigned": 216_000,
    },
    "BANKMATCH-F05": {
        "executable": True,
        "amount": 108_000,
        "candidate_confidences": (30, 30),
        "decision": "unmatched",
        "assigned": 0,
    },
    "BANKMATCH-F06": {
        "executable": True,
        "original_payment": 108_000,
        "reversal_amount": -108_000,
        "path": "reversal",
        "reference_match": "end_to_end_reference",
        "net_paid": 0,
        "open_after": 108_000,
        "status_after": "open",
        "guard_handoff": "payment_returned",
    },
    "BANKMATCH-F07": {
        "executable": True,
        "amount": 108_000,
        "candidate_signals": ((20, 30, 15, 0, 0), (20, 30, 0, 0, 0)),
        "candidate_confidences": (65, 50),
        "decision": "needs_review",
        "ranks": (1, 2),
        "assigned_before_confirmation": 0,
    },
    "BANKMATCH-F08": {
        "executable": True,
        "amount": 108_000,
        "bank_booking_date": "2026-07-28",
        "due_date": "2026-08-03",
        "signals": (60, 30, 0, 0, 5),
        "confidence": 95,
        "decision": "auto_match",
        "settlement_order": "designated_period",
        "assigned": 108_000,
        "status_after": "settled",
        "paid_in_advance": True,
        "missing_period_receivable_result": "credit",
    },
    "BANKMATCH-F09": {
        "executable": True,
        "amount": 108_000,
        "counterpart_iban": None,
        "signals": (0, 30, 15, 0, 0),
        "confidence": 45,
        "decision": "needs_review",
        "assigned_before_confirmation": 0,
        "iban_learned": False,
    },
    "BANKMATCH-F10": {
        "executable": True,
        "decimal_imports": (("1080.00", 108_000), ("1080.005", 108_001)),
        "rounding": "decimal_round_half_up_to_cent",
    },
    "BANKMATCH-F11": {
        "executable": True,
        "expected": 108_000,
        "payment": 100_000,
        "signals": (60, 0, 0, 0, 0),
        "confidence": 60,
        "decision": "auto_match",
        "nominal_components": (85_000, 15_000, 8_000),
        "paid_components": (78_704, 13_889, 7_407),
        "open_after": 8_000,
        "status_after": "partial",
        "nk_advance_paid": 13_889,
    },
    "BANKMATCH-F12": {
        "executable": True,
        "statement_nachzahlung": 24_500,
        "receivable_expected": 24_500,
        "payment": 24_500,
        "signals": (60, 30, 0, 0, 0),
        "confidence": 90,
        "decision": "auto_match",
        "settlement_order": "designated_receivable",
        "category": "nk_nachzahlung",
        "assigned": 24_500,
        "status_after": "settled",
    },
    "BANKMATCH-F13": {
        "executable": True,
        "amount": 108_000,
        "initial_signals": (0, 30, 10, 0, 0),
        "initial_confidence": 40,
        "initial_decision": "needs_review",
        "assigned_before_confirmation": 0,
        "learns_non_null_iban_after_confirmation": True,
        "following_month_unique_iban_signal": 60,
        "following_month_decision": "auto_match",
    },
}
